[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name="plate-vision-pipeline"
version="0.1.0"
requires-python = ">=3.13,<3.14"
dynamic=["dependencies"]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
